//
//  SplashWorker.swift
//  ShopClient
//
//  Created by Evgeniy Antonov on 10/6/17.
//  Copyright (c) 2017 Evgeniy Antonov. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

class SplashWorker {
    func loadShopInfo(callback: @escaping (_ shop: Shop?, _ error: Error?) -> ()) {
        RepositoryRepo.shared.getShop(callback: { (shopObject, error) in
            callback(shopObject, error)
        })
    }
    
    func loadCategories(callback: @escaping (_ categories: [Category]?, _ error: Error?) -> ()) {
        RepositoryRepo.shared.getCategoryList(perPage: 0) { (categories, error) in
            callback(categories, error)
        }
    }
}
