//
//  SplashPresenter.swift
//  ShopClient
//
//  Created by Evgeniy Antonov on 10/6/17.
//  Copyright (c) 2017 Evgeniy Antonov. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol SplashPresentationLogic {
    func presentShopInfo(response: Splash.Remote.Response)
    func presentCategories(response: Splash.Remote.Response)
}

class SplashPresenter: SplashPresentationLogic {
    weak var viewController: SplashDisplayLogic?
        
    func presentShopInfo(response: Splash.Remote.Response) {
        if let error = response.error?.localizedDescription {
            let viewModel = Splash.Remote.ViewModel(errorMessage: error)
            viewController?.showErrorMessage(with: viewModel)
        }
        viewController?.loadCategories()
    }
    
    func presentCategories(response: Splash.Remote.Response) {
        if let error = response.error?.localizedDescription {
            let viewModel = Splash.Remote.ViewModel(errorMessage: error)
            viewController?.showErrorMessage(with: viewModel)
        } else {
            viewController?.navigateToHome()
        }
    }
}
