//
//  SplashPresenter.swift
//  ShopClient
//
//  Created by Evgeniy Antonov on 10/6/17.
//  Copyright (c) 2017 Evgeniy Antonov. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol SplashPresentationLogic {
    func presentShopInfo(response: Splash.Something.Response)
}

class SplashPresenter: SplashPresentationLogic {
    weak var viewController: SplashDisplayLogic?
        
    func presentShopInfo(response: Splash.Something.Response) {
        let viewModel = Splash.Something.ViewModel(shop: response.shop, error: response.error)
        viewController?.displayShopInfo(viewModel: viewModel)
    }
}
