//
//  SplashInteractor.swift
//  ShopClient
//
//  Created by Evgeniy Antonov on 10/6/17.
//  Copyright (c) 2017 Evgeniy Antonov. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol SplashBusinessLogic {
    func loadShopInfo(request: Splash.Remote.Request)
}

protocol SplashDataStore {
}

class SplashInteractor: SplashBusinessLogic, SplashDataStore {
    var presenter: SplashPresentationLogic?
    var worker: SplashWorker?
    
    func loadShopInfo(request: Splash.Remote.Request) {
        worker = SplashWorker()
        worker?.loadShopInfo(callback: { [weak self] (shop, error) in
            let response = Splash.Remote.Response(error: error)
            self?.presenter?.presentShopInfo(response: response)
        })
    }
}
