//
//  SplashModels.swift
//  ShopClient
//
//  Created by Evgeniy Antonov on 10/6/17.
//  Copyright (c) 2017 Evgeniy Antonov. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum Splash {
    // MARK: Use cases
    enum Remote {
        struct Request {
        }
        
        struct Response {
            var error: Error?
        }
        
        struct ViewModel {
            var errorMessage: String?
        }
    }
}
